---
application:
  name: "appdemo-usage-bot"
  project: "appdemo-usage-bot"
  organization: "QoveryCommunity"
routers:
- name: "main-appdemo-usage-bot"
  routes:
  - application_name: "appdemo-usage-bot"
    paths:
    - "/*"
